name: Run unit tests on MPS Backend
on:
  push:
    paths:
      - "ignite/**"
      - "tests/ignite/**"
      - "tests/run_code_style.sh"
      - "examples/**.py"
      - "requirements-dev.txt"
      - ".github/workflows/mps-tests.yml"
  pull_request:
    paths:
      - "ignite/**"
      - "tests/ignite/**"
      - "tests/run_code_style.sh"
      - "examples/**.py"
      - "requirements-dev.txt"
      - ".github/workflows/unit-tests.yml"
  workflow_dispatch:

concurrency:
  # <workflow_name>-<branch_name>-<true || commit_sha (if branch is protected)>
  group: mps-tests-${{ github.ref_name }}-${{ !(github.ref_protected) || github.sha }}
  cancel-in-progress: true

# Cherry-picked from https://github.com/pytorch/test-infra/blob/main/.github/workflows/linux_job.yml

jobs:
  mps-tests:    
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        pytorch-channel: [pytorch, pytorch-nightly]
        runner: ['macos-m1-12']
    uses: pytorch/test-infra/.github/workflows/macos_job.yml@main
    with:
        repository: pytorch/ignite
          # We need an increased timeout here, since the macos-12 runner is the free one from GH
          # and needs roughly 2 hours to just run the test suite
        timeout: 240
        runner: ${{ matrix.runner }}
        script: |
          set -euo pipefail

          export PYTHON_VERSION=${{ matrix.python-version }}

          ## Normal tests for mps
          bash tests/run_mps_tests.sh 2

          # Check training on cifar10, run without backend
          ## initial run
          CI=1 python examples/contrib/cifar10/main.py run --checkpoint_every=200 --stop_iteration=500
          
          ## resume
          CI=1 python examples/contrib/cifar10/main.py run --checkpoint_every=200 --num_epochs=7 --resume-from=/tmp/output-cifar10/resnet18_backend-None-1_stop-on-500/training_checkpoint_400.pt
          